version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - 8000:80
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - 3000:3000
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: finitiOne

volumes:
  mysql_data:
